

cache: packages

sudo: false

r_github_packages:
  - r-lib/covr

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
      language: r
      r: oldrel

    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
      language: r
      r: release
      after_success: Rscript -e 'covr::codecov()'

    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
      language: r
      r: devel

    - os: linux
      dist: xenial
      language: python
      python: 3.5
      script:
        - python3 setup.py install
        - python3 tests/test_all.py

    - os: linux
      dist: xenial
      language: python
      python: 3.6
      script:
        - python3 setup.py install
        - python3 tests/test_all.py

    - os: linux
      dist: xenial
      language: python
      python: 3.7-dev
      script:
        - python3 setup.py install
        - python3 tests/test_all.py

    - os: osx
      osx_image: xcode8.3
      language: r
      r: release

    - os: osx
      osx_image: xcode8.3
      language: generic
      before_install:
        - brew update
        - brew upgrade python
        #- brew install python3
        #- pip3 install numpy distutils_pytest pytest
      script:
        - python3 setup.py install
        - python3 tests/test_all.py

  allow_failures:
    - python: "3.7-dev"

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

